name: inventory_manager_app
description: A Flutter app for managing inventory

publish_to: 'none' # Remove this line if you want to publish to the Flutter package repository.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2 # Provider for state management (optional)
  cupertino_icons: ^1.0.0 # Ensure this is correct version for null safety

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
