// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7N5wc2iw-w9GS2IpEdfRSNLv1gBXQy8Q',
    appId: '1:333034661476:web:b0cc27fe407dcedc432171',
    messagingSenderId: '333034661476',
    projectId: 'inventoryapp-414c7',
    authDomain: 'inventoryapp-414c7.firebaseapp.com',
    storageBucket: 'inventoryapp-414c7.firebasestorage.app',
    measurementId: 'G-YD8Y757677',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnb843aachXxBtITn3mFVzMlL_yXjBJoA',
    appId: '1:333034661476:android:700860479fc0c37e432171',
    messagingSenderId: '333034661476',
    projectId: 'inventoryapp-414c7',
    storageBucket: 'inventoryapp-414c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc7aC3GbVGspIyi0x9MDvKe7nDUj22Cnc',
    appId: '1:333034661476:ios:f9bb6a0452e03a66432171',
    messagingSenderId: '333034661476',
    projectId: 'inventoryapp-414c7',
    storageBucket: 'inventoryapp-414c7.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc7aC3GbVGspIyi0x9MDvKe7nDUj22Cnc',
    appId: '1:333034661476:ios:f9bb6a0452e03a66432171',
    messagingSenderId: '333034661476',
    projectId: 'inventoryapp-414c7',
    storageBucket: 'inventoryapp-414c7.firebasestorage.app',
    iosBundleId: 'com.example.inventoryManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7N5wc2iw-w9GS2IpEdfRSNLv1gBXQy8Q',
    appId: '1:333034661476:web:4db99d89bdbe09b8432171',
    messagingSenderId: '333034661476',
    projectId: 'inventoryapp-414c7',
    authDomain: 'inventoryapp-414c7.firebaseapp.com',
    storageBucket: 'inventoryapp-414c7.firebasestorage.app',
    measurementId: 'G-0DZ4QD4884',
  );
}
